import { Property, Client, Request, User } from "./types";

export const sampleProperties: Property[] = [
  {
    id: "1",
    operation: "بيع",
    propertyType: "شقة",
    city: "بوسكورة",
    district: "الحي الأول",
    address: "شارع الحسن الثاني",
    price: 65000000,
    area: 120,
    rooms: 3,
    salons: 2,
    bathrooms: 2,
    kitchens: 1,
    floor: 3,
    garage: true,
    elevator: true,
    balcony: true,
    garden: false,
    pool: false,
    guard: true,
    facade: "شمالية",
    view: "حديقة",
    year: 2020,
    status: "متوفر",
    negotiable: true,
    rent: 0,
    mortgage: 0,
    images: [
      "https://picsum.photos/seed/bouskoura1/600/400.jpg",
      "https://picsum.photos/seed/bouskoura2/600/400.jpg",
    ],
    video: "",
    description: "شقة فاخرة في حي هادئ في بوسكورة",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    operation: "كراء",
    propertyType: "شقة مفروشة",
    city: "الرباط",
    district: "أكدال",
    address: "شارع محمد الخامس",
    price: 0,
    area: 100,
    rooms: 2,
    salons: 1,
    bathrooms: 2,
    kitchens: 1,
    floor: 5,
    garage: true,
    elevator: true,
    balcony: true,
    garden: false,
    pool: false,
    guard: true,
    facade: "جنوبية",
    view: "بحر",
    year: 2022,
    status: "متوفر",
    negotiable: false,
    rent: 8000,
    mortgage: 0,
    images: [
      "https://picsum.photos/seed/rabat1/600/400.jpg",
      "https://picsum.photos/seed/rabat2/600/400.jpg",
    ],
    video: "",
    description: "شقة مفروشة في أكدال، أطلالة على البحر",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    operation: "بيع",
    propertyType: "فيلا",
    city: "المحمدية",
    district: "الساحل",
    address: "شارع الراية",
    price: 150000000,
    area: 300,
    rooms: 5,
    salons: 3,
    bathrooms: 4,
    kitchens: 2,
    floor: 0,
    garage: true,
    elevator: false,
    balcony: true,
    garden: true,
    pool: true,
    guard: true,
    facade: "شمالية",
    view: "بحر",
    year: 2018,
    status: "متوفر",
    negotiable: true,
    rent: 0,
    mortgage: 0,
    images: [
      "https://picsum.photos/seed/mohammedia1/600/400.jpg",
      "https://picsum.photos/seed/mohammedia2/600/400.jpg",
    ],
    video: "",
    description: "فيلا فاخرة على الشاطئ في المحمدية",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    operation: "بيع",
    propertyType: "أرض",
    city: "سيدي موسى",
    district: "المنطقة الصناعية",
    address: "طريق الدار البيضاء",
    price: 25000000,
    area: 500,
    rooms: 0,
    salons: 0,
    bathrooms: 0,
    kitchens: 0,
    floor: 0,
    garage: false,
    elevator: false,
    balcony: false,
    garden: false,
    pool: false,
    guard: false,
    facade: "",
    view: "",
    year: 0,
    status: "تم البيع",
    negotiable: false,
    rent: 0,
    mortgage: 0,
    images: ["https://picsum.photos/seed/sidi1/600/400.jpg"],
    video: "",
    description: "أرض زراعية في سيدي موسى",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    operation: "كراء",
    propertyType: "مكتب",
    city: "الدار البيضاء",
    district: "المازنة",
    address: "شارع الحسن الثاني",
    price: 0,
    area: 60,
    rooms: 2,
    salons: 1,
    bathrooms: 1,
    kitchens: 0,
    floor: 2,
    garage: true,
    elevator: true,
    balcony: false,
    garden: false,
    pool: false,
    guard: true,
    facade: "غربية",
    view: "شارع",
    year: 2021,
    status: "تم الكراء",
    negotiable: false,
    rent: 5000,
    mortgage: 0,
    images: ["https://picsum.photos/seed/mazena1/600/400.jpg"],
    video: "",
    description: "مكتب مجهز في المازنة",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    operation: "بيع",
    propertyType: "محل تجاري",
    city: "الرباط",
    district: "الحي المحمدي",
    address: "شارع الإغريق",
    price: 40000000,
    area: 80,
    rooms: 1,
    salons: 0,
    bathrooms: 1,
    kitchens: 0,
    floor: 0,
    garage: false,
    elevator: false,
    balcony: false,
    garden: false,
    pool: false,
    guard: false,
    facade: "جنوبية",
    view: "شارع",
    year: 2015,
    status: "متوفر",
    negotiable: true,
    rent: 0,
    mortgage: 0,
    images: ["https://picsum.photos/seed/med1/600/400.jpg"],
    video: "",
    description: "محل تجاري في شارع حيوي",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    operation: "بيع",
    propertyType: "شقة",
    city: "عين الحق",
    district: "الحي السابع",
    address: "شارع الماء",
    price: 55000000,
    area: 110,
    rooms: 3,
    salons: 2,
    bathrooms: 2,
    kitchens: 1,
    floor: 4,
    garage: true,
    elevator: true,
    balcony: true,
    garden: false,
    pool: false,
    guard: false,
    facade: "شرقية",
    view: "حديقة",
    year: 2019,
    status: "متوفر",
    negotiable: true,
    rent: 0,
    mortgage: 0,
    images: [
      "https://picsum.photos/seed/ainhaq1/600/400.jpg",
      "https://picsum.photos/seed/ainhaq2/600/400.jpg",
    ],
    video: "",
    description: "شقة حديثة في عين الحق",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    operation: "رهن",
    propertyType: "شقة",
    city: "الرباط",
    district: "الأغوال",
    address: "شارع الوحدة",
    price: 80000000,
    area: 140,
    rooms: 4,
    salons: 2,
    bathrooms: 3,
    kitchens: 1,
    floor: 6,
    garage: true,
    elevator: true,
    balcony: true,
    garden: false,
    pool: false,
    guard: true,
    facade: "شمالية",
    view: "مدينة",
    year: 2020,
    status: "متوفر",
    negotiable: false,
    rent: 0,
    mortgage: 40000000,
    images: ["https://picsum.photos/seed/agdal1/600/400.jpg"],
    video: "",
    description: "شقة كبيرة في الأغوال",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "9",
    operation: "كراء",
    propertyType: "شقة",
    city: "بوسكورة",
    district: "الحي الثاني",
    address: "شارع التضامن",
    price: 0,
    area: 90,
    rooms: 2,
    salons: 1,
    bathrooms: 1,
    kitchens: 1,
    floor: 2,
    garage: false,
    elevator: true,
    balcony: false,
    garden: false,
    pool: false,
    guard: false,
    facade: "غربية",
    view: "شارع",
    year: 2017,
    status: "متوفر",
    negotiable: true,
    rent: 4500,
    mortgage: 0,
    images: ["https://picsum.photos/seed/bouskoura3/600/400.jpg"],
    video: "",
    description: "شقة اقتصادية في بوسكورة",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "10",
    operation: "بيع",
    propertyType: "فيلا",
    city: "الدار البيضاء",
    district: "انفا",
    address: "شارع البحر",
    price: 200000000,
    area: 400,
    rooms: 6,
    salons: 4,
    bathrooms: 5,
    kitchens: 2,
    floor: 0,
    garage: true,
    elevator: false,
    balcony: true,
    garden: true,
    pool: true,
    guard: true,
    facade: "جنوبية",
    view: "بحر",
    year: 2016,
    status: "متوفر",
    negotiable: true,
    rent: 0,
    mortgage: 0,
    images: [
      "https://picsum.photos/seed/anfa1/600/400.jpg",
      "https://picsum.photos/seed/anfa2/600/400.jpg",
    ],
    video: "",
    description: "فيلا فاخرة في انفا على البحر",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const sampleClients: Client[] = [
  {
    id: "1",
    name: "أحمد بنعلي",
    phone: "0600112233",
    whatsapp: "0600112233",
    city: "الدار البيضاء",
    notes: "يبحث عن شقة في بوسكورة",
    createdAt: new Date(),
  },
  {
    id: "2",
    name: "فاطمة الزهراء",
    phone: "0611223344",
    whatsapp: "0611223344",
    city: "الرباط",
    notes: "تبحث عن فيلا في المحمدية",
    createdAt: new Date(),
  },
  {
    id: "3",
    name: "كريم العلوي",
    phone: "0622334455",
    whatsapp: "0622334455",
    city: "المحمدية",
    notes: "يبحث عن شقة مفروشة",
    createdAt: new Date(),
  },
  {
    id: "4",
    name: "سارة المصدقي",
    phone: "0633445566",
    whatsapp: "0633445566",
    city: "الرباط",
    notes: "تبحث عن أرض في سيدي موسى",
    createdAt: new Date(),
  },
  {
    id: "5",
    name: "يوسف الحسني",
    phone: "0644556677",
    whatsapp: "0644556677",
    city: "الدار البيضاء",
    notes: "يبحث عن رهن شقة",
    createdAt: new Date(),
  },
];

export const sampleRequests: Request[] = [
  {
    id: "1",
    clientId: "1",
    clientName: "أحمد بنعلي",
    operation: "شراء",
    propertyType: "شقة",
    budgetMin: 50000000,
    budgetMax: 70000000,
    city: "بوسكورة",
    district: "",
    rooms: 3,
    area: 100,
    mortgage: false,
    notes: "حاجة 3 غرف على الأقل",
    status: "جديد",
    createdAt: new Date(),
  },
  {
    id: "2",
    clientId: "2",
    clientName: "فاطمة الزهراء",
    operation: "شراء",
    propertyType: "فيلا",
    budgetMin: 100000000,
    budgetMax: 200000000,
    city: "المحمدية",
    district: "",
    rooms: 5,
    area: 250,
    mortgage: false,
    notes: "مع مسبح وحديقة",
    status: "جديد",
    createdAt: new Date(),
  },
  {
    id: "3",
    clientId: "3",
    clientName: "كريم العلوي",
    operation: "كراء",
    propertyType: "شقة مفروشة",
    budgetMin: 7000,
    budgetMax: 10000,
    city: "الرباط",
    district: "",
    rooms: 2,
    area: 90,
    mortgage: false,
    notes: "بشاطئ البحر",
    status: "جديد",
    createdAt: new Date(),
  },
  {
    id: "4",
    clientId: "4",
    clientName: "سارة المصدقي",
    operation: "شراء",
    propertyType: "أرض",
    budgetMin: 20000000,
    budgetMax: 30000000,
    city: "سيدي موسى",
    district: "",
    rooms: 0,
    area: 400,
    mortgage: false,
    notes: "زراعية",
    status: "جديد",
    createdAt: new Date(),
  },
  {
    id: "5",
    clientId: "5",
    clientName: "يوسف الحسني",
    operation: "رهن",
    propertyType: "شقة",
    budgetMin: 30000000,
    budgetMax: 50000000,
    city: "الرباط",
    district: "",
    rooms: 3,
    area: 120,
    mortgage: true,
    notes: "",
    status: "جديد",
    createdAt: new Date(),
  },
  {
    id: "6",
    clientId: "1",
    clientName: "أحمد بنعلي",
    operation: "شراء",
    propertyType: "شقة",
    budgetMin: 45000000,
    budgetMax: 60000000,
    city: "عين الحق",
    district: "",
    rooms: 2,
    area: 90,
    mortgage: false,
    notes: "",
    status: "جديد",
    createdAt: new Date(),
  },
];

export const sampleUsers: User[] = [
  {
    uid: "1",
    name: "مدير الموقع",
    email: "admin@aqari.ma",
    role: "مدير",
  },
  {
    uid: "2",
    name: "موظف مبيعات",
    email: "user@aqari.ma",
    role: "موظف",
  },
];

export const initialCounters = {
  propertyCounter: 11,
  requestCounter: 7,
  clientCounter: 6,
};
